-- MySQL Script generated by MySQL Workbench
-- Thu Nov  3 14:52:02 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema vendas_sucos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vendas_sucos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vendas_sucos` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `vendas_sucos` ;

-- -----------------------------------------------------
-- Table `vendas_sucos`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vendas_sucos`.`clientes` (
  `cpf` VARCHAR(11) NOT NULL,
  `nome` VARCHAR(100) NULL DEFAULT NULL,
  `data_nascimento` DATE NULL DEFAULT NULL,
  `idade` TINYINT NULL DEFAULT NULL,
  `sexo` CHAR(1) NULL DEFAULT NULL,
  `cep` VARCHAR(8) NULL DEFAULT NULL,
  `endereco` VARCHAR(150) NULL DEFAULT NULL,
  `bairro` VARCHAR(45) NULL DEFAULT NULL,
  `cidade` VARCHAR(45) NULL DEFAULT NULL,
  `estado` VARCHAR(2) NULL DEFAULT NULL,
  `limite_credito` FLOAT NULL DEFAULT NULL,
  `volume_compra` FLOAT NULL DEFAULT NULL,
  `primeira_compra` BIT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`cpf`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vendas_sucos`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vendas_sucos`.`produtos` (
  `codigo` VARCHAR(10) NOT NULL,
  `descricao` VARCHAR(100) NULL DEFAULT NULL,
  `sabor` VARCHAR(50) NULL DEFAULT NULL,
  `tamanho` VARCHAR(50) NULL DEFAULT NULL,
  `embalagem` VARCHAR(50) NULL DEFAULT NULL,
  `preco` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vendas_sucos`.`vendedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vendas_sucos`.`vendedores` (
  `matricula` VARCHAR(5) NOT NULL,
  `nome` VARCHAR(100) NULL DEFAULT NULL,
  `bairro` VARCHAR(50) NULL DEFAULT NULL,
  `comissao` FLOAT NULL DEFAULT NULL,
  `data_admissao` DATE NULL DEFAULT NULL,
  `ferias` BIT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`matricula`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vendas_sucos`.`notas_fiscais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vendas_sucos`.`notas_fiscais` (
  `numero` VARCHAR(5) NOT NULL,
  `data_venda` DATE NOT NULL,
  `cpf_cliente` VARCHAR(11) NOT NULL,
  `matricula_vendedor` VARCHAR(5) NOT NULL,
  `imposto` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`numero`),
  INDEX `cpf_cliente` (`cpf_cliente` ASC) VISIBLE,
  INDEX `matricula_vendedor` (`matricula_vendedor` ASC) VISIBLE,
  CONSTRAINT `FK_cliente`
    FOREIGN KEY (`cpf_cliente`)
    REFERENCES `vendas_sucos`.`clientes` (`cpf`),
  CONSTRAINT `FK_vendedor`
    FOREIGN KEY (`matricula_vendedor`)
    REFERENCES `vendas_sucos`.`vendedores` (`matricula`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vendas_sucos`.`itens_notas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vendas_sucos`.`itens_notas` (
  `numero` VARCHAR(5) NOT NULL,
  `codigo_produto` VARCHAR(10) NOT NULL,
  `quantidade` INT NULL DEFAULT NULL,
  `preco` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`numero`, `codigo_produto`),
  INDEX `codigo_produto` (`codigo_produto` ASC) VISIBLE,
  CONSTRAINT `FK_codigo_produto`
    FOREIGN KEY (`codigo_produto`)
    REFERENCES `vendas_sucos`.`produtos` (`codigo`),
  CONSTRAINT `FK_numero_nota`
    FOREIGN KEY (`numero`)
    REFERENCES `vendas_sucos`.`notas_fiscais` (`numero`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
